#!/usr/bin/env python3
"""Generate Roadguard's offline MapLibre styles into app/src/main/assets/map/.

Two styles are produced, day and night, over the **Shortbread 1.0** vector schema. They are
generated rather than hand-written so the two palettes cannot drift apart, and so the layer budget
stays visible in one place.

Design notes that matter more than they look:

* **Nineteen layers, not two hundred.** MapLibre issues draw calls per visible layer per tile per
  frame, and the baseline device has a single-shader-core Mali-G57. The published Shortbread styles
  run 200-324 layers, most of them POI icons and land-use fills a driver does not need. Roadguard
  draws land, water, the road network, boundaries, road and place labels, and a vehicle puck.

* **The whole road network is two layers.** Shortbread guarantees features are ordered by z-order
  within a tile (motorways before residential, tunnels before bridges), so one casing layer plus one
  fill layer, with width and colour selected by a `match` on `kind`, renders the hierarchy correctly.
  That replaces twelve per-class layer pairs with two.

* **Zoom 14 is the archive's maximum; the map displays up to 18.** MapLibre overzooms z14 geometry,
  which is exactly right for driving: no storage is spent on zoom levels whose only extra detail is
  sub-building geometry nobody reads at 100 km/h.

* **`__PMTILES_URI__`** is substituted at runtime with `pmtiles://file:///<abs path>`, because the
  archive's absolute path is only known on the device.

* Glyphs and sprites are `asset://`, so a style load performs no network I/O whatsoever.

Run from the repository root:  python3 tools/generate_map_styles.py
"""

from __future__ import annotations

import json
import os
import sys

OUT = os.path.join("app", "src", "main", "assets", "map")
SOURCE = "roadguard"
ATTRIBUTION = (
    '<a href="https://www.openstreetmap.org/copyright" target="_blank">'
    "&copy; OpenStreetMap contributors</a>"
)

DAY = {
    "name": "Roadguard Day",
    "background": "#EEF1F4",
    "ocean": "#AFD3E8",
    "water": "#AFD3E8",
    "water_line": "#8FBFDA",
    "forest": "#CFE0C3",
    "green": "#D8E8CD",
    "sand": "#EFE6CF",
    "urban": "#E5E3E0",
    "wetland": "#CFE0DE",
    "building": "#DCDFE3",
    "road_fill_major": "#FFFFFF",
    "road_fill_primary": "#FFF6D9",
    "road_fill_minor": "#FFFFFF",
    "road_casing_major": "#E1A15A",
    "road_casing_primary": "#D8B76A",
    "road_casing_minor": "#C9CFD4",
    "rail": "#B0B7BD",
    "ferry": "#7FA9C4",
    "boundary": "#9AA3AA",
    "label": "#22282C",
    "label_halo": "#FFFFFFDD",
    "label_minor": "#4A5257",
    "vehicle": "#0E6E96",
    "vehicle_halo": "#33CEFB",
}

NIGHT = {
    "name": "Roadguard Night",
    "background": "#0E1215",
    "ocean": "#0A1D28",
    "water": "#0C2431",
    "water_line": "#123245",
    "forest": "#122019",
    "green": "#14231A",
    "sand": "#1E1D17",
    "urban": "#171A1D",
    "wetland": "#10201F",
    "building": "#1A2024",
    "road_fill_major": "#5C6A73",
    "road_fill_primary": "#4A555D",
    "road_fill_minor": "#333C42",
    "road_casing_major": "#8A6A3A",
    "road_casing_primary": "#5E5540",
    "road_casing_minor": "#1E252A",
    "rail": "#2C3439",
    "ferry": "#2A4A5C",
    "boundary": "#3A444B",
    "label": "#DDE4E9",
    "label_halo": "#000000CC",
    "label_minor": "#A9B2B8",
    "vehicle": "#33CEFB",
    "vehicle_halo": "#0E6E96",
}

MAJOR = ["motorway", "trunk"]
PRIMARY = ["primary"]
SECONDARY = ["secondary", "tertiary"]

# Road width by zoom, with a per-class multiplier chosen by `kind`. The stops are deliberately
# sparse: MapLibre interpolates between them, and every extra stop is arithmetic per vertex.
ROAD_WIDTH = [
    "interpolate", ["linear"], ["zoom"],
    5, ["match", ["get", "kind"], MAJOR, 0.7, PRIMARY, 0.4, 0.0],
    9, ["match", ["get", "kind"], MAJOR, 1.6, PRIMARY, 1.1, SECONDARY, 0.7, 0.3],
    13, ["match", ["get", "kind"], MAJOR, 5.0, PRIMARY, 4.0, SECONDARY, 2.8, 1.4],
    17, ["match", ["get", "kind"], MAJOR, 17.0, PRIMARY, 13.0, SECONDARY, 10.0, 6.0],
]

ROAD_CASING_WIDTH = [
    "interpolate", ["linear"], ["zoom"],
    9, ["match", ["get", "kind"], MAJOR, 2.8, PRIMARY, 2.2, SECONDARY, 1.6, 0.9],
    13, ["match", ["get", "kind"], MAJOR, 7.4, PRIMARY, 6.2, SECONDARY, 4.6, 2.8],
    17, ["match", ["get", "kind"], MAJOR, 22.0, PRIMARY, 18.0, SECONDARY, 14.0, 9.0],
]


def road_colour(palette: dict[str, str], casing: bool) -> list:
    suffix = "casing" if casing else "fill"
    return [
        "match", ["get", "kind"],
        MAJOR, palette[f"road_{suffix}_major"],
        PRIMARY, palette[f"road_{suffix}_primary"],
        palette[f"road_{suffix}_minor"],
    ]


def style(palette: dict[str, str]) -> dict:
    return {
        "version": 8,
        "name": palette["name"],
        "metadata": {
            "roadguard:note": "Generated by tools/generate_map_styles.py. Do not hand-edit.",
            "roadguard:schema": "Shortbread 1.0",
        },
        "glyphs": "asset://map/glyphs/{fontstack}/{range}.pbf",
        "sprite": [{"id": "basics", "url": "asset://map/sprites/basics/sprites"}],
        "sources": {
            SOURCE: {
                "type": "vector",
                "url": "__PMTILES_URI__",
                "attribution": ATTRIBUTION,
            },
        },
        "layers": [
            {
                "id": "background",
                "type": "background",
                "paint": {"background-color": palette["background"]},
            },
            {
                "id": "ocean",
                "type": "fill",
                "source": SOURCE,
                "source-layer": "ocean",
                "paint": {"fill-color": palette["ocean"]},
            },
            {
                "id": "land",
                "type": "fill",
                "source": SOURCE,
                "source-layer": "land",
                "minzoom": 7,
                "paint": {
                    # The `kind` values are exactly those the Shortbread producer emits, so urban
                    # land use reads as urban instead of falling through to a green default.
                    "fill-color": [
                        "match", ["get", "kind"],
                        ["forest", "wood"], palette["forest"],
                        ["sand", "beach", "scree", "shingle", "bare_rock", "quarry"], palette["sand"],
                        ["bog", "marsh", "string", "swamp", "wet_meadow", "fen"], palette["wetland"],
                        [
                            "residential", "commercial", "industrial", "retail", "garages",
                            "railway", "brownfield", "greenfield", "landfill",
                        ], palette["urban"],
                        palette["green"],
                    ],
                    "fill-opacity": 0.75,
                },
            },
            {
                "id": "water",
                "type": "fill",
                "source": SOURCE,
                "source-layer": "water_polygons",
                "paint": {"fill-color": palette["water"]},
            },
            {
                "id": "water-lines",
                "type": "line",
                "source": SOURCE,
                "source-layer": "water_lines",
                "minzoom": 9,
                "paint": {
                    "line-color": palette["water_line"],
                    "line-width": ["interpolate", ["linear"], ["zoom"], 9, 0.5, 16, 3.0],
                },
            },
            {
                "id": "buildings",
                "type": "fill",
                "source": SOURCE,
                "source-layer": "buildings",
                "minzoom": 15,
                "paint": {"fill-color": palette["building"], "fill-opacity": 0.7},
            },
            {
                "id": "streets-casing",
                "type": "line",
                "source": SOURCE,
                "source-layer": "streets",
                "minzoom": 9,
                "filter": ["!=", ["get", "rail"], True],
                "layout": {"line-cap": "round", "line-join": "round"},
                "paint": {
                    "line-color": road_colour(palette, casing=True),
                    "line-width": ROAD_CASING_WIDTH,
                },
            },
            {
                "id": "streets",
                "type": "line",
                "source": SOURCE,
                "source-layer": "streets",
                "filter": ["!=", ["get", "rail"], True],
                "layout": {"line-cap": "round", "line-join": "round"},
                "paint": {
                    "line-color": road_colour(palette, casing=False),
                    "line-width": ROAD_WIDTH,
                    # Tunnels are drawn faded rather than hidden, so a driver can still see that the
                    # road continues underneath.
                    "line-opacity": ["case", ["==", ["get", "tunnel"], True], 0.45, 1.0],
                },
            },
            {
                "id": "rail",
                "type": "line",
                "source": SOURCE,
                "source-layer": "streets",
                "minzoom": 11,
                "filter": ["==", ["get", "rail"], True],
                "paint": {
                    "line-color": palette["rail"],
                    "line-width": ["interpolate", ["linear"], ["zoom"], 11, 0.6, 16, 2.0],
                    "line-dasharray": [3, 3],
                },
            },
            {
                "id": "ferries",
                "type": "line",
                "source": SOURCE,
                "source-layer": "ferries",
                "minzoom": 10,
                "paint": {
                    "line-color": palette["ferry"],
                    "line-width": 1.2,
                    "line-dasharray": [2, 3],
                },
            },
            {
                "id": "boundary-state",
                "type": "line",
                "source": SOURCE,
                "source-layer": "boundaries",
                "minzoom": 5,
                "filter": [">=", ["get", "admin_level"], 4],
                "paint": {
                    "line-color": palette["boundary"],
                    "line-width": 0.8,
                    "line-dasharray": [4, 3],
                },
            },
            {
                "id": "boundary-country",
                "type": "line",
                "source": SOURCE,
                "source-layer": "boundaries",
                "filter": ["<=", ["get", "admin_level"], 2],
                "paint": {
                    "line-color": palette["boundary"],
                    "line-width": ["interpolate", ["linear"], ["zoom"], 2, 0.6, 8, 1.6],
                },
            },
            {
                "id": "street-labels",
                "type": "symbol",
                "source": SOURCE,
                "source-layer": "street_labels",
                "minzoom": 13,
                "layout": {
                    "symbol-placement": "line",
                    "text-field": ["coalesce", ["get", "name"], ["get", "ref"]],
                    "text-font": ["noto_sans_regular"],
                    "text-size": ["interpolate", ["linear"], ["zoom"], 13, 10, 18, 14],
                    "text-max-angle": 30,
                    "text-padding": 4,
                },
                "paint": {
                    "text-color": palette["label"],
                    "text-halo-color": palette["label_halo"],
                    "text-halo-width": 1.4,
                },
            },
            {
                "id": "place-labels-major",
                "type": "symbol",
                "source": SOURCE,
                "source-layer": "place_labels",
                "filter": ["in", ["get", "kind"], ["literal", ["capital", "state_capital", "city"]]],
                "layout": {
                    "text-field": ["get", "name"],
                    "text-font": ["noto_sans_bold"],
                    "text-size": ["interpolate", ["linear"], ["zoom"], 3, 11, 8, 16, 13, 20],
                    "text-max-width": 8,
                },
                "paint": {
                    "text-color": palette["label"],
                    "text-halo-color": palette["label_halo"],
                    "text-halo-width": 1.6,
                },
            },
            {
                "id": "place-labels-minor",
                "type": "symbol",
                "source": SOURCE,
                "source-layer": "place_labels",
                "minzoom": 8,
                "filter": [
                    "!",
                    ["in", ["get", "kind"], ["literal", ["capital", "state_capital", "city"]]],
                ],
                "layout": {
                    "text-field": ["get", "name"],
                    "text-font": ["noto_sans_regular"],
                    "text-size": ["interpolate", ["linear"], ["zoom"], 8, 10, 14, 15],
                    "text-max-width": 8,
                },
                "paint": {
                    "text-color": palette["label_minor"],
                    "text-halo-color": palette["label_halo"],
                    "text-halo-width": 1.4,
                },
            },
            {
                "id": "boundary-labels",
                "type": "symbol",
                "source": SOURCE,
                "source-layer": "boundary_labels",
                "maxzoom": 8,
                "layout": {
                    "text-field": ["get", "name"],
                    "text-font": ["noto_sans_bold"],
                    "text-size": ["interpolate", ["linear"], ["zoom"], 3, 10, 7, 14],
                    "text-transform": "uppercase",
                    "text-letter-spacing": 0.12,
                },
                "paint": {
                    "text-color": palette["label_minor"],
                    "text-halo-color": palette["label_halo"],
                    "text-halo-width": 1.4,
                },
            },
            # The vehicle marker is fed from Roadguard's own location engine, not MapLibre's
            # location component: that keeps the map out of the permission and GNSS business
            # entirely, and means map throttling cannot affect the recorder's location updates.
            {
                "id": "vehicle-halo",
                "type": "circle",
                "source": "vehicle",
                "paint": {
                    "circle-radius": ["interpolate", ["linear"], ["zoom"], 8, 10, 16, 22],
                    "circle-color": palette["vehicle_halo"],
                    "circle-opacity": 0.25,
                    "circle-stroke-width": 0,
                },
            },
            {
                "id": "vehicle-dot",
                "type": "circle",
                "source": "vehicle",
                "paint": {
                    "circle-radius": ["interpolate", ["linear"], ["zoom"], 8, 4.5, 16, 8],
                    "circle-color": palette["vehicle"],
                    "circle-stroke-color": "#FFFFFF",
                    "circle-stroke-width": 2,
                },
            },
        ],
    }


def main() -> None:
    if not os.path.isdir("app/src/main"):
        sys.exit("run from the repository root")
    os.makedirs(OUT, exist_ok=True)
    for palette, name in ((DAY, "style-day.json"), (NIGHT, "style-night.json")):
        document = style(palette)
        # The vehicle source is declared here rather than in `style()` so both styles share it.
        document["sources"]["vehicle"] = {
            "type": "geojson",
            "data": {"type": "FeatureCollection", "features": []},
        }
        path = os.path.join(OUT, name)
        with open(path, "w", encoding="utf-8") as handle:
            json.dump(document, handle, indent=2)
            handle.write("\n")
        print(f"{path}  {os.path.getsize(path)} B  {len(document['layers'])} layers")


if __name__ == "__main__":
    main()
